// Static site build for HomeTree. Run: node scripts/build.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { icon, ICON_PATHS } from './lib/icons.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');
const SITE_URL = process.env.URL || 'https://hometree-hosts.netlify.app';
const AMAZON_TAG = process.env.AMAZON_TAG || '';
// Netlify sets CONTEXT to production, branch-deploy or deploy-preview. Local builds count as preview.
const IS_PREVIEW = (process.env.CONTEXT || 'local') !== 'production';
const YEAR = 2026;

// Generate browser icon module used by card.js, then import shared modules.
fs.writeFileSync(path.join(ROOT, 'src/js/icons.js'), `// Generated by build.mjs from scripts/lib/icons.mjs\nexport const P = ${JSON.stringify(ICON_PATHS)};\n`);
const { productCard, normalize, ROOMS } = await import('../src/js/card.js');
const { GUIDES, TOPICS, PHOTOS } = await import('../content/guides.mjs');
const { MESSAGES, CHECKLISTS, PRINTABLES } = await import('../content/templates.mjs');
const PRODUCTS = normalize(JSON.parse(fs.readFileSync(path.join(ROOT, 'data/products.json'), 'utf8')), AMAZON_TAG);

const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const ph = (key, w = 1200) => `https://images.unsplash.com/${PHOTOS[key].src}?auto=format&fit=crop&w=${w}&q=72`;
function img(key, { sizes = '100vw', cls = '', eager = false, ratio = null } = {}) {
  const p = PHOTOS[key];
  const crop = ratio ? `&ar=${ratio}` : '';
  const srcset = [480, 800, 1200, 1600].map((w) => `${ph(key, w)}${crop} ${w}w`).join(', ');
  return `<img class="${cls}" src="${ph(key, 1200)}${crop}" srcset="${srcset}" sizes="${sizes}" alt="${esc(p.alt)}" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
}

// ---------- Shared pieces ----------
const NAV = [
  ['Guides', '/guides/', 'guides'],
  ['Gear', '/gear/', 'gear'],
  ['Tools', '/tools/', 'tools'],
  ['Free guide', '/free-guide/', 'gift'],
  ['Templates', '/templates/', 'templates'],
];
const TOOLS = [
  { slug: 'revenue-calculator', title: 'Revenue and profit calculator', short: 'Revenue and profit', ico: 'trending', text: 'Monthly profit, booked nights and the break-even point for your rental.' },
  { slug: 'cleaning-fee-calculator', title: 'Cleaning fee calculator', short: 'Cleaning fee', ico: 'receipt', text: 'Turn cleaner pay, laundry and supplies into a fee that still books short stays.' },
  { slug: 'restock-calculator', title: 'Restock calculator', short: 'Restock', ico: 'cart', text: 'A monthly shopping list for toilet paper, coffee, soap and more, based on your bookings.' },
];
const MENU_LABEL = { 'price-your-rental': 'Pricing your rental', 'hire-and-manage-cleaners': 'Hiring cleaners', 'get-great-reviews': 'Getting great reviews', 'listing-photos': 'Listing photos', 'listing-title-description': 'Title and description', 'furnish-your-rental': 'Furnishing, room by room', 'self-check-in': 'Self check-in', 'restock-supplies': 'Restocking supplies' };
const topicIcon = { Pricing: 'dollar', Operations: 'sparkles', Reviews: 'star', Listing: 'camera', Setup: 'gear', 'For landlords': 'landlord' };

function signupForm({ source, button = 'Send me the guide', note = true, dark = false, name = false, hosting = false, success, results = false, id }) {
  return `<form class="signup js-signup" novalidate ${results ? 'data-results="1"' : ''} ${success ? `data-success="${esc(success)}"` : ''}>
  <input type="hidden" name="source" value="${esc(source)}">
  <label class="hp" aria-hidden="true">Company<input name="company" tabindex="-1" autocomplete="off"></label>
  ${name ? `<div class="field"><label for="${id}-name">First name <span class="muted" style="font-weight:500">(optional)</span></label><input class="input" id="${id}-name" name="firstName" autocomplete="given-name"></div>` : ''}
  ${hosting ? `<div class="field"><label for="${id}-host">How many rentals do you host?</label><select class="input" id="${id}-host" name="hosting"><option value="">Choose one</option><option>Planning my first</option><option>1 listing</option><option>2 to 5 listings</option><option>6 or more</option><option>Long-term rentals</option></select></div>` : ''}
  <div class="signup-row">
    <label class="sr-only" for="${id}-email">Email address</label>
    <input class="input" id="${id}-email" type="email" name="email" placeholder="you@email.com" autocomplete="email" required>
    <button class="btn ${dark ? 'btn-reverse' : 'btn-primary'}" type="submit">${button}</button>
  </div>
  <div class="form-msg" role="status" aria-live="polite"></div>
  ${note ? `<p class="form-note">Free. No spam. Unsubscribe anytime. <a href="/privacy/">Privacy</a></p>` : ''}
</form>`;
}

function guideCard(g, { big = false, row = false, first = false } = {}) {
  const cls = ['card', 'reveal', row ? 'row' : '', big ? 'big' : ''].filter(Boolean).join(' ');
  return `<a class="${cls}" href="/guides/${g.slug}/" data-topic="${esc(g.topic)}" data-text="${esc((g.title + ' ' + g.excerpt + ' ' + g.topic).toLowerCase())}" ${first ? 'data-first="1"' : ''}>
  <div class="card-media leaf-tl">${img(g.photo, { sizes: big ? '(min-width: 900px) 700px, 100vw' : '(min-width: 1024px) 400px, (min-width: 640px) 50vw, 100vw' })}</div>
  <div class="card-body">
    <span class="eyebrow${g.landlord ? ' landlord' : ''}">${esc(g.topic)}</span>
    <h3 class="card-title">${esc(g.title)}</h3>
    ${row ? '' : `<p class="card-text">${esc(g.excerpt)}</p>`}
    <div class="card-meta">${icon('clock')}<span>${g.minutes} min read</span></div>
  </div>
</a>`;
}

function menuPanel() {
  const g = (title, ico, links) => `<div class="menu-group"><h3>${icon(ico)}${title}</h3><ul>${links.map(([l, h]) => `<li><a href="${h}">${l}${icon('chevron', 'i-sm')}</a></li>`).join('')}</ul></div>`;
  return `<div class="menu-scrim" data-close-menu></div>
<nav class="menu-panel" id="site-menu" aria-label="Full menu" inert>
  <div class="menu-top">
    <a class="logo" href="/" aria-label="HomeTree home"><img src="/assets/mark-green.svg" alt="" width="34" height="34"><span class="word">Home<em>Tree</em></span></a>
    <button class="menu-close" type="button" data-close-menu>${icon('x', 'i-sm')}CLOSE</button>
  </div>
  <div class="menu-grid">
    <div class="menu-feature">
      <span class="eyebrow" style="color:#c8eb9a">Free guide</span>
      <h3>Grow a better rental</h3>
      <p>Our free playbook on revenue, reviews, cleaners and setup. Straight to your inbox.</p>
      <a class="btn btn-reverse" href="/free-guide/">Get the free guide</a>
    </div>
    ${g('Start here', 'sprout', [['Home', '/'], ['Free guide', '/free-guide/'], ['All guides', '/guides/'], ['About HomeTree', '/about/']])}
    ${g('Guides by topic', 'guides', GUIDES.filter((x) => !x.landlord).map((x) => [MENU_LABEL[x.slug] || x.title, `/guides/${x.slug}/`]))}
    ${g('Tools', 'tools', TOOLS.map((t) => [t.short, `/tools/${t.slug}/`]).concat([['All tools', '/tools/']]))}
    ${g('Gear by room', 'gear', [['Kitchen', '/gear/?room=Kitchen'], ['Bedroom', '/gear/?room=Bedroom'], ['Bathroom', '/gear/?room=Bathroom'], ['Entry and living', '/gear/?room=Entry&room=Living+room'], ['Starter kit', '/gear/?kit=Starter+kit'], ['All gear', '/gear/']])}
    ${g('Templates', 'templates', [['Guest messages', '/templates/#messages'], ['Checklists', '/templates/#checklists'], ['Printable cards', '/templates/#printables']])}
    ${g('For landlords', 'landlord', [['Screen tenants', '/guides/screen-tenants/'], ['Landlord guides', '/guides/?topic=For+landlords']])}
  </div>
</nav>`;
}

// Default social sharing card (1200x630). Guide articles use their own photo instead.
// Source design: scripts/og-card.html. Re-render it with Playwright if the copy or logo changes.
const SHARE_IMAGE = SITE_URL + '/assets/og-image.png';
const SHARE_ALT = 'HomeTree logo. Free guides, tools and templates to help Airbnb and VRBO hosts earn more and get better reviews.';

function layout({ title, description, pathname, body, active = '', scripts = [], bodyAttrs = '', image = SHARE_IMAGE, head = '' }) {
  const full = title ? `${title} | HomeTree` : 'HomeTree | Grow a better rental';
  const url = SITE_URL + pathname;
  const navLink = ([l, h, ico], i) => `<a href="${h}" ${active === h ? 'aria-current="page"' : ''} ${ico === 'gift' ? 'class="feature"' : ''}><span class="ico">${icon(ico)}</span>${l}</a>`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(full)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${url}">
<meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#121a0e" media="(prefers-color-scheme: dark)">
<meta property="og:type" content="website">
<meta property="og:site_name" content="HomeTree">
<meta property="og:title" content="${esc(full)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${url}">
<meta property="og:image" content="${esc(image)}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">${image === SHARE_IMAGE ? `
<meta property="og:image:alt" content="${esc(SHARE_ALT)}">` : ''}
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="${esc(image)}">
<link rel="icon" href="/assets/favicon.png" type="image/png">
<link rel="icon" href="/assets/mark-green.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preconnect" href="https://images.unsplash.com">
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;1,500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/css/site.css?v=${BUILD_ID}">
${head}
${IS_PREVIEW ? '<meta name="robots" content="noindex, nofollow">' : ''}
</head>
<body class="has-bottom-nav" ${bodyAttrs}>
<a class="skip" href="#main">Skip to content</a>
${IS_PREVIEW ? `<div class="preview-bar">Preview of unpublished changes. <a href="https://hometree-hosts.netlify.app${esc(pathname)}">See the live page</a></div>` : ''}
<header class="site-header">
  <div class="container">
    <a class="logo" href="/" aria-label="HomeTree home"><img src="/assets/mark-green.svg" alt="" width="34" height="34"><span class="word">Home<em>Tree</em></span></a>
    <nav class="top-nav" aria-label="Main">${NAV.filter((n) => n[2] !== 'gift').map(([l, h]) => `<a href="${h}" ${active === h ? 'aria-current="page"' : ''}>${l}</a>`).join('')}</nav>
    <div class="header-actions">
      <a class="btn btn-primary btn-sm header-cta" href="/free-guide/">Get the free guide</a>
      <button class="menu-btn" type="button" aria-controls="site-menu" aria-expanded="false">${icon('menu', 'i-sm')}MENU</button>
    </div>
  </div>
</header>
${menuPanel()}
<main id="main">
${body}
</main>
<footer class="site-footer">
  <div class="container">
    <div class="footer-grid">
      <div class="footer-brand">
        <img src="/assets/mark-white.svg" alt="HomeTree" width="56" height="56">
        <p class="ftag">Grow a better rental.</p>
        <p class="small" style="opacity:.85">Free tips, tools and templates for short-term rental hosts. Built by hosts, for hosts.</p>
      </div>
      <div class="footer-col"><h4>Guides</h4><ul>${GUIDES.slice(0, 5).map((g) => `<li><a href="/guides/${g.slug}/">${esc(g.title.replace(/^How to /, '').replace(/^./, (c) => c.toUpperCase()))}</a></li>`).join('')}</ul></div>
      <div class="footer-col"><h4>Tools</h4><ul>${TOOLS.map((t) => `<li><a href="/tools/${t.slug}/">${t.short}</a></li>`).join('')}<li><a href="/templates/">Templates</a></li></ul></div>
      <div class="footer-col"><h4>Shop</h4><ul><li><a href="/gear/">All gear</a></li><li><a href="/gear/?kit=Starter+kit">Starter kit</a></li><li><a href="/gear/?kit=Kitchen+kit">Kitchen kit</a></li><li><a href="/disclosure/">Affiliate disclosure</a></li></ul></div>
      <div class="footer-col"><h4>HomeTree</h4><ul><li><a href="/about/">About</a></li><li><a href="/free-guide/">Free guide</a></li><li><a href="/guides/?topic=For+landlords">For landlords</a></li><li><a href="/privacy/">Privacy</a></li></ul></div>
    </div>
    <div class="legal"><span>&copy; ${YEAR} Social Upgrades, LLC. All rights reserved.</span><span>HomeTree is a brand of Social Upgrades, LLC.</span></div>
  </div>
</footer>
<nav class="bottom-nav" aria-label="Quick links">${NAV.map(navLink).join('')}</nav>
<div class="toast" id="toast" role="status" aria-live="polite">${icon('check', 'i-sm')}<span></span></div>
<script type="module" src="/js/app.js?v=${BUILD_ID}"></script>
${scripts.map((s) => `<script type="module" src="/js/${s}?v=${BUILD_ID}"></script>`).join('\n')}
</body>
</html>`;
}
const BUILD_ID = Date.now().toString(36);

const pages = [];
const page = (pathname, opts) => pages.push({ pathname, html: layout({ pathname, ...opts }) });

// ---------- Home ----------
{
  const feat = GUIDES.filter((g) => g.featured);
  const picks = PRODUCTS.filter((p) => p.featured).slice(0, 4);
  const quick = [
    ['/guides/', 'guides', 'Guides', `${GUIDES.length} practical how-tos`],
    ['/gear/', 'gear', 'Gear', `${PRODUCTS.length} picks, room by room`],
    ['/tools/', 'tools', 'Tools', 'Calculators for profit, fees, supplies'],
    ['/templates/', 'templates', 'Templates', 'Guest messages and checklists'],
    ['/free-guide/', 'gift', 'Free guide', 'The host playbook, free', true],
  ];
  const body = `
<section class="hero">
  <div class="container">
    <div class="hero-copy">
      <span class="eyebrow">Free tips, tools and templates for hosts</span>
      <h1 class="display">Grow a better rental.</h1>
      <p class="lead">Practical advice for Airbnb and VRBO hosts who want more bookings, better reviews and less stress. Everything here is free.</p>
      ${signupForm({ source: 'home-hero', button: 'Get the free guide', id: 'hero' })}
      <div class="proof"><span>${icon('check')}Pricing, cleaners, reviews</span><span>${icon('check')}${PRODUCTS.length} gear picks</span><span>${icon('check')}3 free calculators</span></div>
    </div>
    <div class="hero-media">
      <div class="photo">${img('hero', { sizes: '(min-width: 900px) 600px, 100vw', eager: true })}</div>
      <div class="float-card"><span class="eyebrow">Host tip</span><p>Leave toothpaste and a toothbrush out. It costs under 75 cents a stay and shows up in reviews.</p></div>
    </div>
  </div>
</section>

<section class="section tight">
  <div class="container">
    <div class="quick">
      ${quick.map(([h, ico, t, s, f]) => `<a href="${h}" class="reveal ${f ? 'q-feature' : ''}"><span class="q-ico">${icon(ico)}</span><span class="q-title">${t}</span><span class="q-text">${s}</span></a>`).join('')}
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="section-head"><div class="stack"><span class="eyebrow">Start here</span><h2>The guides hosts ask for most</h2></div><a class="arrow-link" href="/guides/">All guides${icon('arrow')}</a></div>
    <div class="mag">
      ${guideCard(feat[0], { big: true })}
      <div class="side">${feat.slice(1, 4).map((g) => guideCard(g, { row: true })).join('')}</div>
    </div>
  </div>
</section>

<section class="section band-mist">
  <div class="container">
    <div class="section-head"><div class="stack"><span class="eyebrow">Gear</span><h2>Small buys guests notice</h2><p class="muted">From USB bedside lamps to spice racks with free refills. Filter by room, price and why it matters.</p></div><a class="arrow-link" href="/gear/">Shop all gear${icon('arrow')}</a></div>
    <div class="hscroll">${picks.map((p) => productCard(p, { compact: true })).join('')}</div>
  </div>
</section>

<section class="section band-green">
  <div class="container">
    <div class="section-head"><div class="stack"><span class="eyebrow" style="color:#c8eb9a">Free tools</span><h2>Run the numbers in a minute</h2></div></div>
    <div class="tool-cards">${TOOLS.map((t) => `<a class="tool-card reveal" href="/tools/${t.slug}/"><span class="t-ico">${icon(t.ico)}</span><h3>${t.title}</h3><p>${t.text}</p><span class="arrow-link">Open the tool${icon('arrow')}</span></a>`).join('')}</div>
  </div>
</section>

<section class="section">
  <div class="container split">
    <div class="stack" style="display:grid;gap:14px">
      <span class="eyebrow">Templates</span>
      <h2>Copy, paste, send</h2>
      <p class="lead">Eight guest messages for every step of a stay, plus turnover checklists and printable Wi-Fi and house rules cards. Add your details once and every template fills itself in.</p>
      <div><a class="btn btn-secondary" href="/templates/">Browse templates</a></div>
    </div>
    <div class="card reveal" style="box-shadow:var(--shadow-md)">
      <div class="card-body">
        <div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><strong class="card-title" style="font-size:18px">Morning-after check-in</strong><span class="tag neutral">${icon('clock', 'i-sm')}Day 2</span></div>
        <div class="tpl"><div class="msg">Hi Sam,\n\nJust checking in. Is everything working and do you have what you need?\n\nIf anything is missing or not quite right, tell me now and I'll get it fixed today.</div></div>
        <p class="caption">This one message catches problems before they turn into reviews.</p>
      </div>
    </div>
  </div>
</section>

<section class="section" style="padding-top:0">
  <div class="container">
    <div class="signup-band">
      <img class="mark-bg" src="/assets/mark-green.svg" alt="">
      <div class="copy"><span class="eyebrow">Free guide</span><h2>The host playbook, free in your inbox</h2><p class="muted">Revenue, reviews, guest experience, cleaners and a full furnishing checklist in one PDF.</p></div>
      ${signupForm({ source: 'home-band', button: 'Send it to me', id: 'band' })}
    </div>
  </div>
</section>`;
  page('/', { title: '', description: 'Free tips, tools and templates for Airbnb and VRBO hosts. Price your rental, manage cleaners, get better reviews and stock your rental.', body });
}

// ---------- Guides index ----------
{
  const ordered = [...GUIDES];
  const body = `
<section class="page-head"><div class="container">
  <span class="eyebrow">Guides</span>
  <h1>Practical guides for hosts</h1>
  <p class="lead">Step-by-step answers to the questions every host runs into. Pricing, cleaners, reviews, photos, setup and more.</p>
</div></section>
<section class="section tight"><div class="container">
  <div class="toolbar">
    <div class="search">${icon('search')}<label class="sr-only" for="guide-search">Search guides</label><input class="input" id="guide-search" type="search" placeholder="Search guides"></div>
    <div class="chips" role="group" aria-label="Filter by topic">${['All', ...TOPICS].map((t) => `<button type="button" class="chip" data-filter-topic="${t}" aria-pressed="${t === 'All'}">${t}</button>`).join('')}</div>
  </div>
  <div class="guide-grid" id="guide-grid">${ordered.map((g, i) => guideCard(g, { first: i === 0 })).join('')}</div>
  <div class="empty" id="guide-empty">No guides match that yet. Try another topic, or <a href="/free-guide/">get the free guide</a>.</div>
</div></section>
<section class="section" style="padding-top:0"><div class="container"><div class="signup-band"><img class="mark-bg" src="/assets/mark-green.svg" alt=""><div class="copy"><span class="eyebrow">New guides</span><h2>Get new guides by email</h2><p class="muted">One short email when something new is up, plus the free host playbook.</p></div>${signupForm({ source: 'guides-index', button: 'Subscribe', id: 'gi' })}</div></div></section>`;
  page('/guides/', { title: 'Guides', description: 'Practical guides for Airbnb and VRBO hosts: pricing, cleaners, reviews, photos, furnishing and self check-in.', body, active: '/guides/' });
}

// ---------- Guide articles ----------
for (const g of GUIDES) {
  const ico = (s) => s.replace(/__TIP_ICON__/g, icon('tip')).replace(/__ICON_(\w+)__/g, (_, n) => icon(n));
  const toolHtml = g.tool ? ico(`<a class="tool-link" href="/tools/${g.tool[0]}/"><span class="t-ico">__ICON_${g.tool[3]}__</span><span><strong>${g.tool[1]}</strong><span>${g.tool[2]}</span></span></a>`) : '';
  let usedTool = false;
  const midpoint = Math.ceil(g.sections.length / 2);
  const secHtml = g.sections.map(([id, h, html], i) => {
    let out = ico(html);
    if (out.includes('__TOOL__')) { out = out.replace('__TOOL__', toolHtml); usedTool = true; }
    let extra = '';
    if (i === midpoint) extra = `<div class="inline-cta"><h3>Get the free host playbook</h3><p>Everything in our guides, organized into one PDF with checklists you can print.</p>${signupForm({ source: 'guide-inline-' + g.slug, button: 'Send it to me', id: 'in-' + g.slug })}</div>`;
    return `<h2 id="${id}">${esc(h)}</h2>${out}${extra}`;
  }).join('\n');
  const toc = `<nav class="toc" aria-label="On this page"><h4>On this page</h4><ol>${g.sections.map(([id, h]) => `<li><a href="#${id}">${esc(h)}</a></li>`).join('')}</ol></nav>`;
  const related = g.related.map((s) => GUIDES.find((x) => x.slug === s)).filter(Boolean);
  const body = `
<section class="article-hero"><div class="container">
  <div style="display:grid;gap:16px">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="/guides/">Guides</a>${icon('chevron')}<a href="/guides/?topic=${encodeURIComponent(g.topic)}">${esc(g.topic)}</a></nav>
    <span class="eyebrow${g.landlord ? ' landlord' : ''}">${g.landlord ? 'For landlords' : esc(g.topic)}</span>
    <h1>${esc(g.title)}</h1>
    <p class="lead">${esc(g.lead)}</p>
    <div class="meta"><span>${icon('clock')}${g.minutes} min read</span><span>${icon('calendar')}Updated October ${YEAR}</span><span>By the HomeTree team</span></div>
  </div>
  <figure class="article-cover" style="margin:0">${img(g.photo, { sizes: '(min-width: 900px) 600px, 100vw', eager: true })}</figure>
</div></section>
<div class="container article-layout">
  <article>
    <details class="toc-mobile"><summary>On this page ${icon('down', 'i-sm')}</summary>${toc}</details>
    <div class="prose">
      ${secHtml}
      ${g.tool && !usedTool ? toolHtml : ''}
      <div class="takeaways"><h3>Key takeaways</h3><ul>${g.takeaways.map((t) => `<li>${esc(t)}</li>`).join('')}</ul></div>
      ${g.disclaimer ? `<p class="disclaimer">${esc(g.disclaimer)}</p>` : ''}
    </div>
  </article>
  <aside class="article-aside"><div class="sticky">
    ${toc}
    <div class="aside-signup"><span class="eyebrow" style="color:#c8eb9a">Free guide</span><h4>The host playbook</h4><p>Revenue, reviews, cleaners and setup in one free PDF.</p>${signupForm({ source: 'guide-aside-' + g.slug, button: 'Send it', dark: true, note: false, id: 'as-' + g.slug })}</div>
  </div></aside>
</div>
<section class="section band-soft"><div class="container">
  <div class="section-head"><div class="stack"><span class="eyebrow">Keep reading</span><h2>Related guides</h2></div><a class="arrow-link" href="/guides/">All guides${icon('arrow')}</a></div>
  <div class="grid grid-3">${related.map((r) => guideCard(r)).join('')}</div>
</div></section>`;
  const head = `<script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@type': 'Article', headline: g.title, description: g.excerpt, image: ph(g.photo, 1200), dateModified: `${YEAR}-10-06`, author: { '@type': 'Organization', name: 'HomeTree' }, publisher: { '@type': 'Organization', name: 'HomeTree', logo: { '@type': 'ImageObject', url: SITE_URL + '/assets/icon-512.png' } } })}</script>`;
  page(`/guides/${g.slug}/`, { title: g.title, description: g.excerpt, body, active: '/guides/', image: ph(g.photo, 1200) + '&h=630', head });
}

// ---------- Gear ----------
{
  const kits = [
    ['Starter kit', 'package', 'The must-haves for a new listing'],
    ['Kitchen kit', 'kitchen', 'A kitchen guests can really cook in'],
  ];
  const body = `
<section class="page-head"><div class="container">
  <span class="eyebrow">Gear</span>
  <h1>Stock your rental</h1>
  <p class="lead">The things that make guests feel looked after and make turnovers easier. Every pick has a reason. Filter by room, price and why it matters.</p>
  <p class="disclosure">${icon('info')}<span>We may earn a small commission from some links, at no cost to you. It never changes what we recommend. <a href="/disclosure/">Disclosure</a></span></p>
</div></section>
<section class="section tight"><div class="container">
  <div class="kit-row">
    ${kits.map(([k, i, s]) => `<button type="button" class="kit" data-kit="${k}" aria-pressed="false"><span class="k-ico">${icon(i)}</span><strong>${k}</strong><span class="k-sub">${s}</span></button>`).join('')}
    <div class="progress-card"><div class="top"><strong>Your setup</strong><span class="small muted" id="progress-text">0 must-haves</span></div><div class="bar"><span id="progress-bar"></span></div><span class="caption">Tap ${icon('check', 'i-sm').replace('class="i i-sm"', 'class="i i-sm" style="width:14px;height:14px;vertical-align:-2px"')} on items you already have. Saved on this device.</span></div>
  </div>
  <div class="gear-layout" style="margin-top:24px">
    <aside class="filters" id="filters-side" aria-label="Filters"></aside>
    <div>
      <div class="gear-bar">
        <div class="row">
          <div class="search">${icon('search')}<label class="sr-only" for="gear-search">Search gear</label><input class="input" id="gear-search" type="search" placeholder="Search gear"></div>
          <button class="filter-btn mobile" type="button" id="open-filters">${icon('sliders', 'i-sm')}Filters<span class="badge" id="filter-badge">0</span></button>
        </div>
        <div class="chips" id="room-chips" role="group" aria-label="Room"></div>
      </div>
      <div class="results-row"><span class="count" id="result-count"></span><label class="sort">Sort<select id="sort"><option value="priority">Must-haves first</option><option value="room">Room</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="newest">Newest</option></select></label></div>
      <div class="product-grid" id="product-grid">${PRODUCTS.map((p) => productCard(p)).join('')}</div>
      <div class="empty" id="gear-empty">Nothing matches those filters. <button class="btn btn-ghost btn-sm" type="button" data-clear>Clear filters</button></div>
    </div>
  </div>
</div></section>
<div class="sheet-scrim" data-close-sheet></div>
<div class="sheet" id="filter-sheet" role="dialog" aria-modal="true" aria-label="Filters" inert>
  <div class="grabber"></div>
  <div class="sheet-head"><h3>Filters</h3><button class="btn btn-ghost btn-sm" type="button" data-clear>Clear all</button></div>
  <div id="filters-sheet"></div>
  <div class="sheet-foot"><button class="btn btn-secondary" type="button" data-close-sheet>Close</button><button class="btn btn-primary" type="button" data-close-sheet id="sheet-apply">Show items</button></div>
</div>
<script type="application/json" id="products-data">${JSON.stringify(PRODUCTS).replace(/</g, '\\u003c')}</script>`;
  page('/gear/', { title: 'Gear: stock your rental', description: 'Recommended furnishings and supplies for Airbnb and VRBO rentals, sorted by room, price and why guests notice them.', body, active: '/gear/', scripts: ['gear.js'] });
}

// ---------- Tools ----------
{
  const body = `
<section class="page-head"><div class="container">
  <span class="eyebrow">Tools</span>
  <h1>Free calculators for hosts</h1>
  <p class="lead">Run the numbers before you set a rate, change a fee or place an order. No sign-up needed, and your inputs stay on your device.</p>
</div></section>
<section class="section tight"><div class="container">
  <div class="tool-grid">${TOOLS.map((t) => `<a class="card tool-tile reveal" href="/tools/${t.slug}/"><div class="t-head"><span class="t-ico">${icon(t.ico)}</span></div><div class="card-body"><h2 class="card-title" style="font-size:22px;line-height:28px">${t.title}</h2><p class="card-text">${t.text}</p><span class="arrow-link" style="margin-top:8px">Open the tool${icon('arrow')}</span></div></a>`).join('')}</div>
</div></section>
<section class="section"><div class="container split">
  <div style="display:grid;gap:14px"><span class="eyebrow">Coming next</span><h2>More tools on the way</h2><p class="lead">A setup budget planner that builds your furnishing list room by room, a photo shot list builder and a message builder. Subscribe and we'll tell you when they're live.</p></div>
  <div class="form-card">${signupForm({ source: 'tools-index', button: 'Notify me', id: 'ti' })}</div>
</div></section>`;
  page('/tools/', { title: 'Tools', description: 'Free calculators for Airbnb hosts: revenue and profit, cleaning fee, and monthly restock list.', body, active: '/tools/' });

  const numField = (id, label, val, { prefix = '', suffix = '', hint = '', step = 1, min = 0, full = false } = {}) => `<div class="field${full ? ' full' : ''}"><label for="${id}">${label}</label><div class="input-wrap${prefix ? ' has-prefix' : ''}${suffix ? ' has-suffix' : ''}">${prefix ? `<span class="prefix">${prefix}</span>` : ''}<input class="input" id="${id}" type="number" inputmode="decimal" value="${val}" min="${min}" step="${step}">${suffix ? `<span class="suffix">${suffix}</span>` : ''}</div>${hint ? `<span class="hint">${hint}</span>` : ''}</div>`;
  const rangeField = (id, label, val, min, max, unit = '') => `<div class="range-field full"><div class="top"><label class="label" for="${id}">${label}</label><output for="${id}">${val}${unit}</output></div><input type="range" id="${id}" min="${min}" max="${max}" value="${val}" data-unit="${unit}"></div>`;
  const emailBox = (slug) => `<div class="email-results no-print"><h3>Email me my results</h3><p class="small muted">We'll send this summary to your inbox and add you to our free host emails. Unsubscribe anytime.</p>${signupForm({ source: 'tool-' + slug, button: 'Email it', results: true, note: false, success: 'Sent. Check your inbox in a minute.', id: 'er-' + slug })}</div>`;
  const actions = `<div class="no-print" style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-secondary btn-sm" type="button" id="copy-results">${icon('copy', 'i-sm')}Copy results</button><button class="btn btn-ghost btn-sm" type="button" id="print-results">${icon('printer', 'i-sm')}Print</button><button class="btn btn-ghost btn-sm" type="button" id="reset-tool">${icon('refresh', 'i-sm')}Reset</button></div>`;
  const toolHead = (t, lead) => `<section class="page-head"><div class="container"><nav class="crumbs" aria-label="Breadcrumb"><a href="/tools/">Tools</a>${icon('chevron')}<span>${t.short}</span></nav><h1>${t.title}</h1><p class="lead">${lead}</p></div></section>`;

  // Revenue
  {
    const t = TOOLS[0];
    const body = toolHead(t, 'Estimate monthly profit and the number of booked nights you need to break even. Change any number and the results update instantly.') + `
<section class="section tight"><div class="container calc">
  <form class="panel" onsubmit="return false">
    <div class="fieldset"><h3>Bookings</h3><div class="fields">
      ${numField('rate', 'Average nightly rate', 180, { prefix: '$' })}
      ${numField('stay', 'Average stay', 3, { suffix: 'nights', step: 0.5, min: 1 })}
      ${rangeField('occ', 'Occupancy', 62, 0, 100, '%')}
    </div></div>
    <div class="fieldset"><h3>Per stay</h3><div class="fields">
      ${numField('cleanfee', 'Cleaning fee you charge', 120, { prefix: '$' })}
      ${numField('platform', 'Platform fee', 3, { suffix: '%', step: 0.5 })}
      ${numField('cleaner', 'Cleaner pay per turnover', 95, { prefix: '$' })}
      ${numField('supplies', 'Laundry and supplies per turnover', 25, { prefix: '$' })}
    </div><span class="hint">Platform fee: Airbnb's split fee is about 3% for hosts. The host-only fee is about 15%. Check your account settings.</span></div>
    <div class="fieldset"><h3>Monthly fixed costs</h3><div class="fields">
      ${numField('mortgage', 'Mortgage or rent', 2400, { prefix: '$' })}
      ${numField('utilities', 'Utilities and internet', 320, { prefix: '$' })}
      ${numField('other', 'Insurance, software and other', 180, { prefix: '$', full: true })}
    </div></div>
  </form>
  <div class="results">
    <div class="result-hero"><span class="label">Monthly profit</span><span class="big" id="r-net">$0</span><span class="sub" id="r-annual"></span></div>
    <div class="stats">
      <div class="stat"><span class="v" id="r-nights">0</span><span class="k">Booked nights a month</span></div>
      <div class="stat"><span class="v" id="r-be">0</span><span class="k">Nights to break even</span></div>
      <div class="stat"><span class="v" id="r-gross">$0</span><span class="k">Monthly gross</span></div>
      <div class="stat"><span class="v" id="r-adr">$0</span><span class="k">Effective nightly rate</span></div>
    </div>
    <div id="r-note"></div>
    <div class="panel" style="gap:12px"><h2>Where the money goes</h2><div class="breakdown" id="r-breakdown"></div><p class="caption">Estimates based on a 30.4-day month. Occupancy taxes are usually collected and paid by the platform, so they are left out.</p></div>
    ${actions}
    ${emailBox(t.slug)}
    <p class="small muted">Next: <a href="/guides/price-your-rental/">How to price your short-term rental</a></p>
  </div>
</div></section>`;
    page(`/tools/${t.slug}/`, { title: t.title, description: 'Free Airbnb revenue and profit calculator. Estimate monthly profit and break-even nights for your rental.', body, active: '/tools/', scripts: ['tools.js'], bodyAttrs: 'data-tool="revenue"' });
  }
  // Cleaning fee
  {
    const t = TOOLS[1];
    const body = toolHead(t, 'Add up what each turnover really costs, then see a cleaning fee that covers it and how it looks to a guest booking 1, 2 or 7 nights.') + `
<section class="section tight"><div class="container calc">
  <form class="panel" onsubmit="return false">
    <div class="fieldset"><h3>Cost per turnover</h3><div class="fields">
      ${numField('cleaner', 'Cleaner pay', 95, { prefix: '$' })}
      ${numField('laundry', 'Laundry', 25, { prefix: '$' })}
      ${numField('supplies', 'Supplies and consumables', 15, { prefix: '$' })}
      ${numField('extra', 'Your time or extras', 0, { prefix: '$' })}
    </div></div>
    <div class="fieldset"><h3>Your listing</h3><div class="fields">
      ${numField('rate', 'Nightly rate', 180, { prefix: '$' })}
      ${numField('stay', 'Typical stay', 3, { suffix: 'nights', step: 0.5, min: 1 })}
      ${rangeField('pass', 'Share of cost passed to guest', 100, 0, 120, '%')}
    </div></div>
  </form>
  <div class="results">
    <div class="result-hero"><span class="label">Suggested cleaning fee</span><span class="big" id="c-fee">$0</span><span class="sub" id="c-sub"></span></div>
    <div class="stats">
      <div class="stat"><span class="v" id="c-eff">$0</span><span class="k">Effective nightly rate</span></div>
      <div class="stat"><span class="v" id="c-share">0%</span><span class="k">Fee share of a typical stay</span></div>
    </div>
    <div id="c-note"></div>
    <div class="panel" style="gap:12px"><h2>What guests see</h2><table class="table-mini"><thead><tr><th>Stay</th><th class="num">Total</th><th class="num">Per night</th><th class="num">Fee share</th></tr></thead><tbody id="c-table"></tbody></table></div>
    ${actions}
    ${emailBox(t.slug)}
    <p class="small muted">Next: <a href="/guides/hire-and-manage-cleaners/">How to hire and manage cleaners</a></p>
  </div>
</div></section>`;
    page(`/tools/${t.slug}/`, { title: t.title, description: 'Free Airbnb cleaning fee calculator. Turn cleaner pay, laundry and supplies into a fee that still books short stays.', body, active: '/tools/', scripts: ['tools.js'], bodyAttrs: 'data-tool="cleaning"' });
  }
  // Restock
  {
    const t = TOOLS[2];
    const body = toolHead(t, 'Tell us about your rental and your bookings, and get a monthly shopping list for the supplies guests use up.') + `
<section class="section tight"><div class="container calc">
  <form class="panel" onsubmit="return false">
    <div class="fieldset"><h3>Your rental</h3><div class="fields">
      ${numField('bedrooms', 'Bedrooms', 2, { min: 1 })}
      ${numField('baths', 'Bathrooms', 1, { min: 1, step: 0.5 })}
      ${numField('guests', 'Average guests per stay', 4, { min: 1 })}
      ${numField('stay', 'Average stay', 3, { suffix: 'nights', step: 0.5, min: 1 })}
      ${rangeField('nights', 'Booked nights per month', 20, 0, 31, '')}
    </div></div>
    <div class="callout"><div class="callout-title">${icon('tip')}How this works</div><p class="small">These are typical usage rates per guest night and per stay. Track what you actually buy for 2 or 3 months, then adjust.</p></div>
  </form>
  <div class="results">
    <div class="stats">
      <div class="stat"><span class="v" id="s-stays">0</span><span class="k">Stays a month</span></div>
      <div class="stat"><span class="v" id="s-gn">0</span><span class="k">Guest nights a month</span></div>
    </div>
    <div class="panel" style="gap:12px"><h2>Monthly shopping list</h2><table class="table-mini"><thead><tr><th>Item</th><th class="num">Per month</th></tr></thead><tbody id="s-table"></tbody></table><p class="caption">Rounded up. Keep 1 to 2 months of everything in a locked owner's closet.</p></div>
    ${actions}
    ${emailBox(t.slug)}
    <p class="small muted">Find bulk packs on the <a href="/gear/?room=Bathroom">Gear page</a>, or read <a href="/guides/restock-supplies/">Restock supplies without running out</a>.</p>
  </div>
</div></section>`;
    page(`/tools/${t.slug}/`, { title: t.title, description: 'Free restock calculator for Airbnb hosts. Get a monthly supply list based on bedrooms, guests and booked nights.', body, active: '/tools/', scripts: ['tools.js'], bodyAttrs: 'data-tool="restock"' });
  }
}

// ---------- Templates ----------
{
  const F = { property: 'Your property', host: 'Your name', checkin: '4 p.m.', checkout: '10 a.m.', wifi: 'Network name', wifipass: 'Password' };
  const fillSpans = (s) => esc(s).replace(/\{(\w+)\}/g, (_, k) => `<span class="ph" data-f="${k}" data-ph="${esc(F[k])}">${esc(F[k])}</span>`).replace(/\[([^\]]+)\]/g, '<span class="ph">[$1]</span>');
  const msgCard = (m) => `<article class="card tpl reveal" id="t-${m.id}"><div class="card-body">
    <div class="head"><div style="display:grid;gap:4px"><h3 class="card-title" style="font-size:19px">${esc(m.title)}</h3><span class="when">${icon('clock')}${esc(m.when)}</span></div><button class="btn btn-secondary btn-sm copy-btn" type="button" data-copy="msg-${m.id}">${icon('copy', 'i-sm')}Copy</button></div>
    <div class="msg" id="msg-${m.id}">${fillSpans(m.body)}</div>
  </div></article>`;
  const checkCard = (c) => `<article class="card tpl reveal"><div class="card-body">
    <div class="head"><div style="display:grid;gap:4px"><h3 class="card-title" style="font-size:19px">${esc(c.title)}</h3><span class="when">${icon('clock')}${esc(c.when)}</span></div><div style="display:flex;gap:6px"><button class="btn btn-secondary btn-sm" type="button" data-copy="cl-${c.id}">${icon('copy', 'i-sm')}Copy</button><button class="btn btn-ghost btn-sm" type="button" data-print="cl-${c.id}" aria-label="Print ${esc(c.title)}">${icon('printer', 'i-sm')}</button></div></div>
    <div class="checklist" id="cl-${c.id}"><h3 class="card-title" style="display:none">${esc(c.title)}</h3>${c.groups.map(([h, items]) => `<h4>${esc(h)}</h4>${items.map((it) => `<label class="check"><input type="checkbox"><span>${esc(it)}</span></label>`).join('')}`).join('')}</div>
  </div></article>`;
  const foot = `<div class="pc-foot"><span>Made with HomeTree</span><img src="/assets/mark-green.svg" alt=""></div>`;
  const printCards = {
    wifi: `<div class="print-card" id="pc-wifi"><span class="pc-eyebrow">Welcome to</span><h3>${fillSpans('{property}')}</h3><div class="hl"><div class="caption" style="color:#5a6650">Wi-Fi network</div><div class="big">${fillSpans('{wifi}')}</div></div><div class="hl"><div class="caption" style="color:#5a6650">Password</div><div class="big">${fillSpans('{wifipass}')}</div></div><p>Trouble connecting? Unplug the router for 30 seconds, then plug it back in. Still stuck? Message ${fillSpans('{host}')}.</p>${foot}</div>`,
    rules: `<div class="print-card" id="pc-rules"><span class="pc-eyebrow">House rules</span><h3>${fillSpans('{property}')}</h3><div class="hl"><strong>Check-in ${fillSpans('{checkin}')}. Checkout ${fillSpans('{checkout}')}.</strong></div><ul><li>Quiet hours 10 p.m. to 8 a.m.</li><li>No smoking inside or on the property.</li><li>No parties or events.</li><li>Please keep the guest count to your booking.</li><li>Tell us right away if something breaks. Accidents happen.</li></ul>${foot}</div>`,
    'checkout-card': `<div class="print-card" id="pc-checkout-card"><span class="pc-eyebrow">Before you go</span><h3>Checkout by ${fillSpans('{checkout}')}</h3><ul><li>Start the dishwasher</li><li>Trash in the outside bins</li><li>Used towels in the bathtub</li><li>Turn off lights and the AC or heat</li><li>Lock the door behind you</li></ul><div class="hl">No need to strip the beds. Thanks for staying with us.</div><p>${fillSpans('{host}')}</p>${foot}</div>`,
  };
  const body = `
<section class="page-head"><div class="container">
  <span class="eyebrow">Templates</span>
  <h1>Guest messages, checklists and printables</h1>
  <p class="lead">Fill in your details once and every template updates. Copy a message straight into Airbnb or VRBO, or print a card for the rental.</p>
</div></section>
<section class="section tight"><div class="container">
  <div class="fill-card">
    <div style="display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap"><strong style="font-family:var(--font-heading);font-size:17px">Your details</strong><button class="btn btn-ghost btn-sm" type="button" id="clear-fields">Clear</button></div>
    <div class="fields">${Object.entries({ property: 'Property name', host: 'Your name', checkin: 'Check-in time', checkout: 'Checkout time', wifi: 'Wi-Fi network', wifipass: 'Wi-Fi password' }).map(([k, l]) => `<div class="field"><label for="f-${k}">${l}</label><input class="input" id="f-${k}" data-field-input="${k}" placeholder="${esc(F[k])}" autocomplete="off"></div>`).join('')}</div>
    <p class="caption">Saved on this device only. Anything in [brackets] is for you to edit per guest.</p>
  </div>
  <div class="tpl-tabs"><div class="chips">${[['messages', `Guest messages (${MESSAGES.length})`], ['checklists', 'Checklists'], ['printables', 'Printable cards']].map(([id, l], i) => `<button type="button" class="chip" data-jump="${id}" aria-pressed="${i === 0}">${l}</button>`).join('')}</div></div>
  <div class="tpl-section" id="messages"><h2>Guest messages</h2><p class="muted">In the order you send them, from booking to checkout.</p><div class="tpl-grid">${MESSAGES.map(msgCard).join('')}</div></div>
  <div class="tpl-section" id="checklists" style="margin-top:48px"><h2>Checklists</h2><p class="muted">Share with your cleaner, or print one for the owner's closet.</p><div class="tpl-grid">${CHECKLISTS.map(checkCard).join('')}</div></div>
  <div class="tpl-section" id="printables" style="margin-top:48px"><h2>Printable cards</h2><p class="muted">5x7 cards that fill in with your details. Print on card stock and frame them.</p>
    <div class="grid grid-3">${PRINTABLES.map((p) => `<div style="display:grid;gap:12px">${printCards[p.id]}<div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><div><strong style="font-family:var(--font-heading)">${esc(p.title)}</strong><div class="caption">${esc(p.when)}</div></div><button class="btn btn-secondary btn-sm" type="button" data-print="pc-${p.id}">${icon('printer', 'i-sm')}Print</button></div></div>`).join('')}</div>
  </div>
</div></section>
<section class="section"><div class="container"><div class="signup-band"><img class="mark-bg" src="/assets/mark-green.svg" alt=""><div class="copy"><span class="eyebrow">Free guide</span><h2>Want the full playbook?</h2><p class="muted">Every message and checklist here, plus revenue, reviews and setup in one free PDF.</p></div>${signupForm({ source: 'templates', button: 'Send it to me', id: 'tp' })}</div></div></section>`;
  page('/templates/', { title: 'Templates', description: 'Free Airbnb guest message templates, turnover checklists and printable Wi-Fi and house rules cards.', body, active: '/templates/', scripts: ['templates.js'] });
}

// ---------- Free guide ----------
{
  const inside = [
    ['Increase your revenue', 'Pricing rules, minimum nights and the weekly 10-minute check.'],
    ['Get better reviews', 'The four messages, fixing problems fast and replying to reviews.'],
    ['Impress your guests', 'The small touches that show up in reviews, and what to skip.'],
    ['Run the rental', 'Hiring and managing cleaners, turnovers, restocking and self check-in.'],
    ['Furnish it right', 'A room-by-room checklist with what to buy and why.'],
  ];
  const body = `
<div class="container fg">
  <div class="cover-wrap"><div class="back"></div>
    <div class="pdf-cover"><img class="wm" src="/assets/mark-white.svg" alt=""><div class="pc-top"><img src="/assets/mark-white.svg" alt="">HomeTree</div><div class="pc-title">Grow a better rental</div><div class="pc-sub">The free host playbook for more bookings, better reviews and less stress.</div><div class="pc-bot"><span>Free from HomeTree</span><span>${YEAR}</span></div></div>
  </div>
  <div class="fg-copy">
    <div style="display:grid;gap:12px"><span class="eyebrow">Free guide</span><h1>The host playbook, free</h1><p class="lead">Everything we know about running a short-term rental, in one PDF you can read in an afternoon and use for years.</p></div>
    <ul class="inside">${inside.map(([t, s], i) => `<li><span class="n">${i + 1}</span><div><strong>${t}</strong><span>${s}</span></div></li>`).join('')}</ul>
    <div class="form-card">${signupForm({ source: 'free-guide', button: 'Send me the guide', name: true, hosting: true, id: 'fg', success: "You're on the list. The guide is on its way to your inbox." })}</div>
  </div>
</div>`;
  page('/free-guide/', { title: 'Free host playbook', description: 'Get the free HomeTree host playbook: increase STR revenue, get better reviews, impress guests, manage cleaners and furnish your rental.', body, active: '/free-guide/' });
}

// ---------- About, privacy, disclosure, 404 ----------
{
  const credits = Object.values(PHOTOS).map((p) => `<li><a href="https://unsplash.com/@${p.user}?utm_source=hometree&utm_medium=referral" rel="noopener">${esc(p.by)}</a></li>`).join('');
  page('/about/', { title: 'About', description: 'HomeTree is a free resource for short-term rental hosts. A brand of Social Upgrades, LLC.', body: `
<section class="page-head"><div class="container"><span class="eyebrow">About</span><h1>Built by hosts, for hosts</h1><p class="lead">HomeTree is a free resource for short-term rental hosts on Airbnb, VRBO and direct booking, plus owners of long-term rentals.</p></div></section>
<section class="section tight"><div class="container split" style="align-items:start">
  <div class="prose">
    <p>We started HomeTree because good hosting advice is scattered across forums, courses and videos that bury the answer. Here, the answer comes first.</p>
    <p>Everything on this site is free: the guides, the calculators, the templates and the free host playbook. We don't hide the good parts behind a sign-up.</p>
    <h2 id="next">What's next</h2>
    <p>We're building a free host dashboard to manage your rentals in one place, with a direct-booking website builder that syncs with Airbnb and VRBO calendars. Later, we'll offer hands-on management for hosts who want it. Subscribe to hear first.</p>
    <h2 id="legal">Who runs HomeTree</h2>
    <p>HomeTree is a brand of Social Upgrades, LLC. Questions or ideas for a guide? Email <a href="mailto:mitchell@socialupgrades.com">mitchell@socialupgrades.com</a>.</p>
    <h2 id="credits">Photo credits</h2>
    <p class="small">Photos from <a href="https://unsplash.com/?utm_source=hometree&utm_medium=referral" rel="noopener">Unsplash</a> by:</p>
    <ul class="small">${credits}</ul>
  </div>
  <div class="form-card"><h3>Get the free host playbook</h3>${signupForm({ source: 'about', button: 'Send it to me', id: 'ab' })}</div>
</div></section>` });

  page('/privacy/', { title: 'Privacy', description: 'How HomeTree handles your email address and data.', body: `
<section class="page-head"><div class="container"><span class="eyebrow">Privacy</span><h1>Privacy policy</h1><p class="lead">Short version: we only collect your email when you give it to us, we use it to send you HomeTree emails, and we never sell it.</p></div></section>
<section class="section tight"><div class="container"><div class="prose">
<h2 id="collect">What we collect</h2><p>When you sign up, we collect your email address and anything else you choose to enter (like your first name or how many rentals you host). Calculator inputs, template details and your gear checklist are saved only in your own browser and never sent to us, unless you choose to email yourself your results.</p>
<h2 id="use">How we use it</h2><p>We use your email to send the free guide, occasional tips and news about HomeTree. Every email has an unsubscribe link. We use Resend to store contacts and send email, and Netlify to host the site.</p>
<h2 id="links">Links to other sites</h2><p>Gear links go to Amazon and other stores. Those sites have their own privacy policies.</p>
<h2 id="contact">Contact</h2><p>HomeTree is a brand of Social Upgrades, LLC. To ask about or delete your data, email <a href="mailto:mitchell@socialupgrades.com">mitchell@socialupgrades.com</a>.</p>
<p class="disclaimer">Last updated October ${YEAR}.</p>
</div></div></section>` });

  page('/disclosure/', { title: 'Affiliate disclosure', description: 'How HomeTree makes money from gear recommendations.', body: `
<section class="page-head"><div class="container"><span class="eyebrow">Disclosure</span><h1>Affiliate disclosure</h1><p class="lead">Some links on HomeTree may be affiliate links. If you buy through them, we may earn a small commission at no extra cost to you.</p></div></section>
<section class="section tight"><div class="container"><div class="prose">
<p>As an Amazon Associate, HomeTree may earn from qualifying purchases. Commissions help keep the guides, tools and templates free.</p>
<p>We only list things we would put in our own rentals, and a commission never changes what we recommend or how we rank it. Prices and availability change often, so we show price ranges instead of exact prices. Check the current price on the store's page before you buy.</p>
</div></div></section>` });

  page('/404/', { title: 'Page not found', description: 'This page could not be found.', body: `
<section class="section"><div class="container" style="display:grid;gap:16px;max-width:640px;text-align:center;justify-items:center">
<img src="/assets/mark-green.svg" alt="" width="72" height="72"><h1>Nothing here yet. Let's grow something.</h1><p class="lead">That page moved or never existed. Try one of these instead.</p>
<div style="display:flex;gap:10px;flex-wrap:wrap;justify-content:center"><a class="btn btn-primary" href="/guides/">Browse guides</a><a class="btn btn-secondary" href="/gear/">Shop gear</a></div>
</div></section>` });
}

// ---------- Write output ----------
fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });
for (const p of pages) {
  const file = p.pathname === '/404/' ? path.join(DIST, '404.html') : path.join(DIST, p.pathname, 'index.html');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, p.html);
}
const copyDir = (from, to) => fs.cpSync(path.join(ROOT, from), path.join(DIST, to), { recursive: true });
copyDir('src/css', 'css');
copyDir('src/js', 'js');
copyDir('assets', 'assets');
copyDir('data', 'data');
fs.writeFileSync(path.join(DIST, 'site.webmanifest'), JSON.stringify({ name: 'HomeTree', short_name: 'HomeTree', start_url: '/', display: 'standalone', background_color: '#ffffff', theme_color: '#539800', icons: [{ src: '/assets/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }, { src: '/assets/icon-512.png', sizes: '512x512', type: 'image/png' }] }));
const urls = pages.filter((p) => p.pathname !== '/404/').map((p) => `<url><loc>${SITE_URL}${p.pathname}</loc></url>`).join('');
fs.writeFileSync(path.join(DIST, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls}</urlset>`);
fs.writeFileSync(path.join(DIST, 'robots.txt'), IS_PREVIEW ? 'User-agent: *\nDisallow: /\n' : `User-agent: *\nAllow: /\nSitemap: ${SITE_URL}/sitemap.xml\n`);
console.log(`Built ${pages.length} pages to dist/ (${PRODUCTS.length} products)`);
